"""Add booking_reference_id to Booking model

Revision ID: 0ceb6cdc601c
Revises: e49b301a5f8e
Create Date: 2025-07-22 11:38:28.202758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ceb6cdc601c'
down_revision: Union[str, Sequence[str], None] = 'e49b301a5f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_reference_id', sa.String(), nullable=True))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_bookings_booking_reference_id'), 'bookings', ['booking_reference_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_reference_id'), table_name='bookings')
    op.alter_column('bookings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookings', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'booking_reference_id')
    # ### end Alembic commands ###
