"""Add public_slug to User model

Revision ID: 46d35d66eb7a
Revises: aa6d22cf130b
Create Date: 2025-07-28 16:51:22.485232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d35d66eb7a'
down_revision: Union[str, Sequence[str], None] = 'aa6d22cf130b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_public_slug'), 'users', ['public_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_slug'), table_name='users')
    op.drop_column('users', 'public_slug')
    # ### end Alembic commands ###
