"""Add owner_id for multi-tenancy support

Revision ID: aa6d22cf130b
Revises: 4d6a593ea021
Create Date: 2025-07-28 16:49:09.912552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6d22cf130b'
down_revision: Union[str, Sequence[str], None] = '4d6a593ea021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_slug'), table_name='users')
    op.drop_column('users', 'public_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_public_slug'), 'users', ['public_slug'], unique=True)
    # ### end Alembic commands ###
