"""Add customer info to bookings table

Revision ID: ec364322d166
Revises: 0ceb6cdc601c
Create Date: 2025-07-22 15:34:56.373073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec364322d166'
down_revision: Union[str, Sequence[str], None] = '0ceb6cdc601c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('customer_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'customer_phone')
    op.drop_column('bookings', 'customer_email')
    op.drop_column('bookings', 'customer_name')
    # ### end Alembic commands ###
